export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_NOTIFICATION_TYPE = 'SET_NOTIFICATION_TYPE';
export const SCREEN_BOTTOM_NAVIGATION = 'SCREEN_BOTTOM_NAVIGATION';
